FROM microsoft/dotnet:sdk

# switch to an app directory
WORKDIR /usr/src/app

COPY . .

# fetch the watch tooling and other package dependencies
# then publish the app so we don't have to build it every change
RUN dotnet restore && \
    dotnet publish -c Release -o ./publish
